feat: orderabled views
ems-project/EMSCoreBundle pull request #836
Opened 2021-11-09 23:20 UTC by theus77

|Q              |A  |
|---------------|---|
|Bug fix?       |n|
|New feature?   |y|	
|BC breaks?     |n|	
|Deprecations?  |n|	
|Fixed tickets  |n|	

Refactor views and reorder them

2021-11-11 14:14 UTC, Davidmattei requested changes
Awesome job! 💯

2021-11-11 14:14 UTC, Davidmattei commented on src/DependencyInjection/Configuration.php
> -    public const APPLICATION_MENU_CONTROLLER = null;
👍

2021-11-11 14:14 UTC, Davidmattei commented on src/Form/Field/PdfSizeType.php
> +
```suggestion
declare(strict_types=1);
```

2021-11-11 18:00 UTC, theus77 commented on src/Form/Field/OrientationType.php
> +
c06235df692d1c37288049afc3053fb6c398a329

2021-11-11 18:01 UTC, theus77 commented on src/Form/Field/PdfSizeType.php
> +
c06235df692d1c37288049afc3053fb6c398a329

2021-11-15 20:24 UTC, Davidmattei approved these changes

2021-11-15 20:24 UTC, merged